[project]
name = "fast-whisper-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "John Kristan Torremocha", email = "torremocha.johnkristan@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "faster-whisper>=1.2.1",
    "nvidia-cublas-cu12>=12.9.2.10",
    "nvidia-cudnn-cu12>=9.25.1.1",
]

[project.scripts]
fast-whisper-app = "fast_whisper_app:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
